on:
  schedule:
    - cron: "52 11 * * 4"
  push:
    branches:
      master


name: Get READMes

jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install curl or something
        run: |
          sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install readr and write READMEs
        run: |
          install.packages("readr");
          install.packages("glue");
          install.packages("blogdown");
          blogdown::install_hugo();
          source("content/posts/readmes/template.R");
          new_temp <- write_template(Sys.Date());
          writeLines(new_temp, "content/posts/readmes/FPLdata.md");
          write(readr::read_file("https://raw.githubusercontent.com/andrewl776/FPLdata/master/README.md"), "content/posts/readmes/FPLdata.md", append = TRUE);
          blogdown::build_site()
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "alittle@mango-solutions.com"
          git config --local user.name "alittle"
          git add --all
          git commit -am "Add READMEs"
          git push

